### ISSUE TITLE
Dataset used for Repo

### ISSUE THREAD

**Issue by malcolm1232** [IS5882/Open-CyKG#2]
Hi a good afternoon from Singapore! 
Sorry, hope you dont mind if i asked afew questions! I do apologise for the lengthy questions!

Question 1
For the following: Open_CyKG_OIE_Model.ipynb
there is a ''' #train_fn="add you file here" '''
I understand you mentioned to get the data from: https://justhalf.github.io/publication/2017-07-01-malwaretextdb
However, from the following lines of codes:
train_textEI = dfE.groupby(dfE['word_id'].eq(0).cumsum())['word'].apply(lambda x: [' '.join(x)]).tolist()
train_predIE =  dfE.groupby(dfE['word_id'].eq(0).cumsum())['pred'].apply(lambda x: [' '.join(x)]).tolist()

I am unable find dataset that has the column 'word_id', 'word' and 'pred'.

Thus i was wondering if you could kindly point me to the direction of the dataset or how u derived the data!

Because from the following link: https://justhalf.github.io/publication/2017-07-01-malwaretextdb
i obtained the following data:
![image 1 ANN TOKENS](https://user-images.githubusercontent.com/66200354/153791920-19b66ab0-367c-495d-9095-888d53db7d4c.png)

i do not see any file which has ['word_id'] and ['word']

Question 2
Also, for the file Open_Cy_KG_NER.ipynb
the codes are as follows:
words = list(dframe['words'].unique()) 
tags = list(dframe['tag'].unique()) 
target = dframe.loc[:,'tag']

class sentence(object):
    def __init__(self, df):
        self.n_sent = 1
        self.df = df
        self.empty = False
        
        agg = lambda s : [(w, p, t) for w, p, t in zip(s['words'].values.tolist(),
                                                       s['POS'].values.tolist(),
                                                       s['tag'].values.tolist())] 
        self.grouped = self.df.groupby("sentence_idx").apply(agg) 
        
Similar question, I was wondering where you got the data from that has "words", "POS", "tag"!

Question 3
Also , i wanted to clarify on some facts; Am i right to say that in order to all the files,
They are prerequisites of one another; Thus they need to be run in the order of the following:
1. OIE
2. NER
3. KnowledgeGraph

Question 4?
im just wondering if you could kindly attach the other relevant datasets if any
Please accept my kindest apologies for the lengthy question! I'm a big fan of ur work and am just trying to get it up!

**Comment by IS5882** [comment]
Thanks you for you nice words. 
1] I uploaded the processed malware DB dataset [here](https://drive.google.com/drive/folders/1zbf2bLLknxEHLJkcVKKmGHnwB9LseCID?usp=sharing)

2] For POS you can use any POS tagger
3] Yes you are right, but it doesn't matter if you do NER first or OIE first, in anyway KG should come in last

**Comment by malcolm1232** [comment]
I requested for an access for the data! I apologise for the inconvenience! 

Thank you for your reply!!

**Comment by nitinpi0210** [comment]
Hello, I have the same trouble as Malcolm here in the format of the malware db dataset that is fed into the OIE model. Can you please give me access to the dataset too? My id is : nitin.pillai@berkeley.edu
