### ISSUE TITLE
Datasets for the notebook

### ISSUE THREAD

**Issue by hvjrocks-ds** [IS5882/Open-CyKG#3]
Hi,
Greetings from India!
I have been following your work for a while and recently I came across your repository, I went through your notebooks but I couldn't find the datasets in the repository which you have used for creating the model. I would be grateful if could share the datasets used in all the 3 notebooks.

Regards,
Harsh Vardhan Jaiswal

**Comment by malcolm1232** [comment]
Hello again Injy Sarhan, I know youre a busy woman! Likewise to @hvjrocks-ds, i have been trying to run the notebook:
Open_CyKG__Knowledge_Graph_Canonicalization.ipynb,

To Narrow down on the dataset for the knowledge graph (Open_CyKG__Knowledge_Graph_Canonicalization.ipynb), 
I was able to run the CY-KG, but i am missing the dataset which requires the following header:

words=df['word']
labels=df['predicted_label']
POS=df['pos']
trueLabels=df['true_label']

df['finalSentID']=df['originalSentID']
df['FinalWord']=df['NERword']

Ner1=df['NERpredicted1']
Ner2=df['NERpredicted2']

Also, there is this line of code (hope it helps!):
df.to_csv("/content/gdrive/MyDrive/my Personal work/Open-CyKG/MalwareDB_dataset_csv_exl/OIEoutput(10Feb).csv", index=False)

A huge thank you in advance!!! :) I hope it doesnt inconvenience you!

**Comment by hvjrocks-ds** [comment]
>

**Comment by hvjrocks-ds** [comment]
Sorry I closed it by mistake.

**Comment by hvjrocks-ds** [comment]
> 

Sorry I closed the issue by mistake. I agree with malcolm on this I am also facing the similar issue. We would be grateful if you could share required datasets for the notebooks.

**Comment by IS5882** [comment]
I updated the public[ Drive folder](https://docs.google.com/spreadsheets/d/1lFZFNOv0ERXUK5yZvTfYPBdILBgYP8_EHaXtK_49OcE/edit?usp=sharing) with the NER data, the data of KG canonicalization is the output of both OIE model and NER model. Let me know if you face any more issues.

**Comment by malcolm1232** [comment]
Thank you for your prompt reply Injy!! Thanks for being so sweet! have a great, great greattt day!!

**Comment by hvjrocks-ds** [comment]
> I updated the public[ Drive folder](https://docs.google.com/spreadsheets/d/1lFZFNOv0ERXUK5yZvTfYPBdILBgYP8_EHaXtK_49OcE/edit?usp=sharing) with the NER data, the data of KG canonicalization is the output of both OIE model and NER model. Let me know if you face any more issues.

Thank you for such quick response.  I went through the above the google drive. Can you please also share the train, dev and test datasets for the OIE model notebook.

**Comment by malcolm1232** [comment]
Oh yes, i have been trying to manipualte the data for OIE, before asking you! Hmmm, by any chance u might have the OIE data? 

It requres the following columns! :
word_id
word
pred
run_id
sent_id
head_pred_id
label

Thank you in advance and have a blessed Thursday!

**Comment by malcolm1232** [comment]
Hiee! I hope i dont trouble you too much again, but may i know if you have the data for OIE model?

As per the codes from the OIE.ipynb : 
          df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
          df.word_id = pd.to_numeric(df.word_id, errors='coerce').astype('Int64')
          df.run_id = pd.to_numeric(df.run_id, errors='coerce').astype('Int64')
          df.sent_id = pd.to_numeric(df.sent_id, errors='coerce').astype('Int64')
          df.head_pred_id = pd.to_numeric(df.head_pred_id, errors='coerce').astype('Int64')

I was wondering if u have the dataset for OIE notebook.
The data you provided was only for NER.ipynb and the dataset you used seemed different! 
I'm terribly sorry for the inconvenience! Just kinda really like ur notebook and have been trying to get it working since then! 

Cheers!

**Comment by nitinpi0210** [comment]
@malcolm1232 @hvjrocks-ds were you able to run the OIE notebook? I tried with the All MDB csv that Sarhan gave but that still doesn't contain all the fields needed to run that notebook : word_id word pred pred_id head_pred_id sent_id run_id label

Did you guys manage to run this? I am waiting for a reply from Sarhan to get some help on this.

**Comment by hvjrocks-ds** [comment]
Hi @nitinpi0210,
I don't have an official data on OIE notebook and I am also facing the same issue like you do. I was able to run only the NER notebook using the data shared by the author.

**Comment by nitinpi0210** [comment]
I have contacted @IS5882 to get the exact malware db dataset that contains all the fields : word_id word pred pred_id head_pred_id sent_id run_id label 

If we can get a dataset containing the above fields, we should be able to run the OIE notebook. Hopefully the author can upload this dataset for us soon.

**Comment by malcolm1232** [comment]
I am able to run to ~block 7, my code is here:  https://colab.research.google.com/drive/1Kh9gsdG2rcySVo-GV5Xc9mW7rx6-pVuW?usp=sharing  

But im facing error with Tensorflow, I put it here for you guys, Would really appreciate if you are able to solve the tensorflow issue!
