### ISSUE TITLE
Dataset for CYKG

### ISSUE THREAD

**Issue by malcolm1232** [IS5882/Open-CyKG#4]
Hello again Injy Sarhan, I know youre a busy woman! I have been trying to run the notebook:
Open_CyKG__Knowledge_Graph_Canonicalization.ipynb,

To Narrow down on the dataset for the knowledge graph (Open_CyKG__Knowledge_Graph_Canonicalization.ipynb),
I was able to run the CY-KG, but i am missing the dataset which requires the following header:

words=df['word']
labels=df['predicted_label']
POS=df['pos']
trueLabels=df['true_label']

df['finalSentID']=df['originalSentID']
df['FinalWord']=df['NERword']

Ner1=df['NERpredicted1']
Ner2=df['NERpredicted2']

Also, there is this line of code (hope it helps!):
df.to_csv("/content/gdrive/MyDrive/my Personal work/Open-CyKG/MalwareDB_dataset_csv_exl/OIEoutput(10Feb).csv", index=False)

A huge thank you in advance!!! :) I hope it doesnt inconvenience you!

**Comment by VICKY-ZZ** [comment]
Oh hi, malcolm! I have the same problem!!! Have you found the dataset???
Thank you so much!!!
