### ISSUE TITLE
Output files for Knowledge Graph

### ISSUE THREAD

**Issue by hvjrocks-ds** [IS5882/Open-CyKG#6]
Hi,
Greetings!
I was going through the Knowledge Graph notebook, I would be extremely grateful if you could share the dataset used in the Knowledge Graph notebook i.e. the output generated from OIE and NER model.

Thanks in advance!
Regards,
Harsh Vardhan Jaiswal

**Comment by VICKY-ZZ** [comment]
Hi, Harsh! I have the same problem! Have you solved it? Thank you so much!!
