### ISSUE TITLE
spacy_wrapper

### ISSUE THREAD

**Issue by malcolm1232** [IS5882/Open-CyKG#7]
Hi 
For the following line of code in OIE.ipynb

> from spacy_wrapper import spacy_whitespace_parser as spacy_ws < 

By any chance u havethe file for it? Because i searched high and low and am unable to find spacy_wrapper library

**Comment by IS5882** [comment]
I added it to the google drive folder https://drive.google.com/drive/folders/1zbf2bLLknxEHLJkcVKKmGHnwB9LseCID?usp=sharing

**Comment by Akchy** [comment]
The python file in the drive seems to be empty, @IS5882 can you please upload the file with code?
