### ISSUE TITLE
OIE Dataset

### ISSUE THREAD

**Issue by malcolm1232** [IS5882/Open-CyKG#8]
Hiee! I hope i dont trouble you too much again, but may i know if you have the data for OIE model?

As per the codes from the OIE.ipynb :
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df.word_id = pd.to_numeric(df.word_id, errors='coerce').astype('Int64')
df.run_id = pd.to_numeric(df.run_id, errors='coerce').astype('Int64')
df.sent_id = pd.to_numeric(df.sent_id, errors='coerce').astype('Int64')
df.head_pred_id = pd.to_numeric(df.head_pred_id, errors='coerce').astype('Int64')

I was wondering if u have the dataset for OIE notebook.
The data you provided was only for NER.ipynb and the dataset you used seemed different!
I'm terribly sorry for the inconvenience! Just kinda really like ur notebook and have been trying to get it working since then!

Cheers!

**Comment by IS5882** [comment]
The data is already available in the google drive public folder that you have access to (MLB_all_csv) divide it into a train, test, dev set with the ratio you desire.

**Comment by l0renor** [comment]
Hi @IS5882 ,
I am Interested in your work as well for my master thesis on MISP kgs.
Can you share the MLB_all_csv and NER data with me as well please.
My mail is l.lukas@hm.edu .
